### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by imanmousaei** [benyamxn/persian-latex#1]
Hi.
I copied the template folder & fonts folder. But when I cant to compile it. It gives the following error:

![Screenshot from 2021-11-16 12-36-24](https://user-images.githubusercontent.com/33493057/141955568-207403e6-6b3a-497c-be6c-96855d1d7b55.png)

**Comment by benyamxn** [comment]
It's just as the error message says, you need to change your compile configuration. Click on the Menu tab at the top left of your screen, then change the compiler to XeLaTex. That should fix it.
